// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/quote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotesEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentQuotes []*PairQuote `protobuf:"bytes,1,rep,name=currentQuotes,proto3" json:"currentQuotes,omitempty"`
}

func (x *QuotesEvent) Reset() {
	*x = QuotesEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotesEvent) ProtoMessage() {}

func (x *QuotesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotesEvent.ProtoReflect.Descriptor instead.
func (*QuotesEvent) Descriptor() ([]byte, []int) {
	return file_proto_quote_proto_rawDescGZIP(), []int{0}
}

func (x *QuotesEvent) GetCurrentQuotes() []*PairQuote {
	if x != nil {
		return x.CurrentQuotes
	}
	return nil
}

type PairQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair   OrderPair `protobuf:"varint,1,opt,name=pair,proto3,enum=proto.OrderPair" json:"pair,omitempty"`
	Price  float64   `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume float64   `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *PairQuote) Reset() {
	*x = PairQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairQuote) ProtoMessage() {}

func (x *PairQuote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairQuote.ProtoReflect.Descriptor instead.
func (*PairQuote) Descriptor() ([]byte, []int) {
	return file_proto_quote_proto_rawDescGZIP(), []int{1}
}

func (x *PairQuote) GetPair() OrderPair {
	if x != nil {
		return x.Pair
	}
	return OrderPair_USD_EUR
}

func (x *PairQuote) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PairQuote) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type MarketDepthEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketDepth []*PairMatketDepth `protobuf:"bytes,1,rep,name=marketDepth,proto3" json:"marketDepth,omitempty"`
}

func (x *MarketDepthEvent) Reset() {
	*x = MarketDepthEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDepthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDepthEvent) ProtoMessage() {}

func (x *MarketDepthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDepthEvent.ProtoReflect.Descriptor instead.
func (*MarketDepthEvent) Descriptor() ([]byte, []int) {
	return file_proto_quote_proto_rawDescGZIP(), []int{2}
}

func (x *MarketDepthEvent) GetMarketDepth() []*PairMatketDepth {
	if x != nil {
		return x.MarketDepth
	}
	return nil
}

type PairMatketDepth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair          OrderPair        `protobuf:"varint,1,opt,name=pair,proto3,enum=proto.OrderPair" json:"pair,omitempty"`
	Direction     OrderDirection   `protobuf:"varint,2,opt,name=direction,proto3,enum=proto.OrderDirection" json:"direction,omitempty"`
	VolumeByPrice []*VolumeByPrice `protobuf:"bytes,3,rep,name=volumeByPrice,proto3" json:"volumeByPrice,omitempty"`
}

func (x *PairMatketDepth) Reset() {
	*x = PairMatketDepth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairMatketDepth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairMatketDepth) ProtoMessage() {}

func (x *PairMatketDepth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairMatketDepth.ProtoReflect.Descriptor instead.
func (*PairMatketDepth) Descriptor() ([]byte, []int) {
	return file_proto_quote_proto_rawDescGZIP(), []int{3}
}

func (x *PairMatketDepth) GetPair() OrderPair {
	if x != nil {
		return x.Pair
	}
	return OrderPair_USD_EUR
}

func (x *PairMatketDepth) GetDirection() OrderDirection {
	if x != nil {
		return x.Direction
	}
	return OrderDirection_BUY
}

func (x *PairMatketDepth) GetVolumeByPrice() []*VolumeByPrice {
	if x != nil {
		return x.VolumeByPrice
	}
	return nil
}

type VolumeByPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume float64 `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *VolumeByPrice) Reset() {
	*x = VolumeByPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeByPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeByPrice) ProtoMessage() {}

func (x *VolumeByPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeByPrice.ProtoReflect.Descriptor instead.
func (*VolumeByPrice) Descriptor() ([]byte, []int) {
	return file_proto_quote_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeByPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *VolumeByPrice) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_proto_quote_proto protoreflect.FileDescriptor

var file_proto_quote_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a,
	0x0b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0d,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69, 0x72,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x09, 0x50, 0x61, 0x69, 0x72, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x10, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x4d, 0x61, 0x74, 0x6b, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x74, 0x68, 0x22, 0xa8, 0x01, 0x0a, 0x0f, 0x50, 0x61, 0x69, 0x72, 0x4d, 0x61, 0x74, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x33, 0x0a,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0d, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x79, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52,
	0x0d, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x3d,
	0x0a, 0x0d, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x08, 0x5a,
	0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_quote_proto_rawDescOnce sync.Once
	file_proto_quote_proto_rawDescData = file_proto_quote_proto_rawDesc
)

func file_proto_quote_proto_rawDescGZIP() []byte {
	file_proto_quote_proto_rawDescOnce.Do(func() {
		file_proto_quote_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_quote_proto_rawDescData)
	})
	return file_proto_quote_proto_rawDescData
}

var file_proto_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_quote_proto_goTypes = []interface{}{
	(*QuotesEvent)(nil),      // 0: proto.QuotesEvent
	(*PairQuote)(nil),        // 1: proto.PairQuote
	(*MarketDepthEvent)(nil), // 2: proto.MarketDepthEvent
	(*PairMatketDepth)(nil),  // 3: proto.PairMatketDepth
	(*VolumeByPrice)(nil),    // 4: proto.VolumeByPrice
	(OrderPair)(0),           // 5: proto.OrderPair
	(OrderDirection)(0),      // 6: proto.OrderDirection
}
var file_proto_quote_proto_depIdxs = []int32{
	1, // 0: proto.QuotesEvent.currentQuotes:type_name -> proto.PairQuote
	5, // 1: proto.PairQuote.pair:type_name -> proto.OrderPair
	3, // 2: proto.MarketDepthEvent.marketDepth:type_name -> proto.PairMatketDepth
	5, // 3: proto.PairMatketDepth.pair:type_name -> proto.OrderPair
	6, // 4: proto.PairMatketDepth.direction:type_name -> proto.OrderDirection
	4, // 5: proto.PairMatketDepth.volumeByPrice:type_name -> proto.VolumeByPrice
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_quote_proto_init() }
func file_proto_quote_proto_init() {
	if File_proto_quote_proto != nil {
		return
	}
	file_proto_order_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_quote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotesEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDepthEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairMatketDepth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeByPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_quote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_quote_proto_goTypes,
		DependencyIndexes: file_proto_quote_proto_depIdxs,
		MessageInfos:      file_proto_quote_proto_msgTypes,
	}.Build()
	File_proto_quote_proto = out.File
	file_proto_quote_proto_rawDesc = nil
	file_proto_quote_proto_goTypes = nil
	file_proto_quote_proto_depIdxs = nil
}
